### ISSUE TITLE
Add Sass tests

### ISSUE THREAD

**Issue by jabley** [alphagov/govuk_frontend_toolkit#124]
After #118, it would be good to add tests to confirm that any Sass changes are good.

This would be an MVP test that it compiles.

**Comment by gemmaleigh** [comment]
There's a `grunt test` task which will check that the Sass compiles and run the scss-lint task to check the scss files against govuk-lint's .scss-lint.yml. 

cc. @dsingleton, @fofr.

**Comment by nickcolley** [comment]
This looks good, will close out :)
