### ISSUE TITLE
Tags are not up to date

### ISSUE THREAD

**Issue by matharden** [alphagov/govuk_frontend_toolkit#204]
Please could you update tags with the version history? The tag revisions are [two years](https://github.com/alphagov/govuk_frontend_toolkit/tree/v0.12.6) out of date, which gives unexpected results when requiring the code via Bower.

**Comment by dsingleton** [comment]
Hey @matharden 

Sorry, we should probably be keeping those up to date.

A while back we switch away from this repo being a distribution repo, with [govuk_frontend_toolkit_gem](https://github.com/alphagov/govuk_frontend_toolkit_gem) and [govuk_frontend_toolkit_npm](https://github.com/alphagov/govuk_frontend_toolkit_npm) using this repo as a source.

But we should still be automatically publishing releases  to support other uses, like yours. It's something we'll look at, but I can't give you an estimate of _when_. In the mean time i'll leave this open as a reminder :+1:

**Comment by matharden** [comment]
Thanks @dsingleton. Tagging this repo is all it would take, which is obviously part of your workflow on other repos. Bower is a great tool for frontend resources, and this is a frontend resource. Problems arise though as you have a 2 year old tag. 

But I appreciate you have stated on the README that it should be included via NPM.

**Comment by dsingleton** [comment]
The automated tagging for the gem comes from our [gem_publisher](https://github.com/alphagov/gem_publisher) (which IIRC is responsible for the old tags here), so we can't get that 'for free'.

In the mean time, is it possible to pin to a SHA with bower? Obviously not ideal, but it would at least give a more expected/fixed result when requiring?

**Comment by matharden** [comment]
Yep. SHA is the way to get the [specific but not necessarily] latest version of this repo.
