### ISSUE TITLE
Stick at top when scrolling/stop scrolling at footer - issues with margins and dynamically changing page lengths

### ISSUE THREAD

**Issue by mattdsmith89** [alphagov/govuk_frontend_toolkit#217]
I have a requirement to fix a summary panel to the right hand side of screen, and it sounded like these two functions provided in the govuk_frontend_toolkit should satisfy the requirement perfectly. However, whilst trying to integrate them into my screen I have encountered two issues, the second of which I have not been able to find a workaround.

Firstly, the height of the fixed element doesn't seem to be computed correctly if there is an element inside it with a margin that extends above the top of this fixed element. In my scenario the fixed div begins with a h3 heading which has the govuk "heading-medium" css class applied. This gives the heading a reasonably large top margin which extends above the fixed parent div. From what I can see, this causes two problems for these functions:
- Initially when scrolling down, the containing div does not become fixed until top of the screen completely passes the margin of the h3 and enters the body of the parent div. At this point the fixed div will appear to "jump" down so that the margin is visible again. I would say that this is unwanted behaviour. 
- Secondly, this also seems to effect the "stop scrolling at footer" calculations, because I have found that in this scenario, the containing div will overflow into the footer an amount roughly equal to the height of the margin at the top. Again, undesirable behaviour.

I have found a workaround for both of these issues; by removing the top margin from the element that overflows the top of the div and adding padding to the div itself (so that the appearance is maintained). The panel then seems to behave as you would expect, thought it is a pain to have to restyle the div and the heading in this way.

The second, more important issue, is the behaviour that is exhibited when the page is dynamically resized. The page that I am trying to use this on has a lot of expandable "details-summary" elements in the main body. Expanding these makes the page longer. I have found that the height of the page is not being recalculated by the "stop scrolling at footer" function, and the panel is stopping well before it reaches the footer. Regardless of the current length of the page, I would expect the panel to reach the footer every time.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this.

Apologies for the lack of response to your issue.
