### ISSUE TITLE
Radio buttons jump up and down on Safari when activated

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_frontend_toolkit#221]
Radio buttons, when activated drop down by about 10 pixels in Safari 8 and 9 on OS X. They jump back up to their original positions when the animation ends.

Test page: http://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons

**Comment by randallNotHopkirk** [comment]
Same here.
Macbook 10.11.3
Safari: 9.03

**Comment by gemmaleigh** [comment]
@robinwhittleton can you please raise this as an issue with GOV.UK elements. [The increase in size of inputs within block labels](https://github.com/alphagov/govuk_elements/pull/98) may have introduced this, I'll test this.
