### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by scottcowan** [alphagov/govuk_frontend_toolkit#233]
Could you add a bower.json to the repo?

I noticed the [bower package](https://libraries.io/bower/govuk_frontend_toolkit/1.4.0) thats registered is linking to a repo that doesn't exist anymore.

cheers

**Comment by tombye** [comment]
Hi @scottcowan, thanks for getting in touch.

We don't maintain a bower package for this code. Can you use the [npm package](https://github.com/alphagov/govuk_frontend_toolkit_npm) instead?

Alternatively, each version bump is tagged so you can pull it down with bower by pointing at this repo with the tag for the version you need.

**Comment by scottcowan** [comment]
Thanks Tom I missed the tags. 

In case anyone is interested you can just use

bower install https://github.com/alphagov/govuk_frontend_toolkit.git#4.6.0

**Comment by dsingleton** [comment]
@tombye how about adding the tag-based approach clearer in the README? It'd fit nicely into the [Other Projects](https://github.com/alphagov/govuk_frontend_toolkit#other-projects) section, along side submodules.

**Comment by tombye** [comment]
@dsingleton good idea, now added.
