### ISSUE TITLE
external-links images not served as image-urls

### ISSUE THREAD

**Issue by Biggsen** [alphagov/govuk_frontend_toolkit#234]
The external-links mixin (_typography.scss) references the images using file-url. This results in the css looking for the images relative to the css file. Hence we got an 'external-links' folder within the css folder containing a few icons, which is very confusing and frankly bad practice. Can that be changed to image-url so that we can use the url_helper and set the path to an images folder of our choosing?

**Comment by edds** [comment]
The `file-url` function is [defined in `_url-helpers.scss`](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_url-helpers.scss) and I think lets you do exactly what you wanted?

**Comment by Biggsen** [comment]
Yep. It's working fine in the toolkit. My govuk_template was referencing the external-links mixin from the toolkit, but not having access to the url_helper. So, there. Closing time.
