### ISSUE TITLE
light blue and hover link blue are very similar

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_frontend_toolkit#240]
Is it worth having two very slightly different light blues? Or just have one?

@markhurrell

**Comment by fofr** [comment]
The `:active` state colour is the same as the `:hover` one.
https://github.com/alphagov/govuk_frontend_toolkit/blob/fbe3ce944b7ebd22e3e965d6f19265c4035354a3/stylesheets/_colours.scss#L94-L95

**Comment by fofr** [comment]
The colour change on hover is a good indicator that the cursor is in the right place. I think that is reason enough to have two blues, but they might benefit from being more different so the effect is clearer.

**Comment by joelanman** [comment]
sorry, thats not what I meant - the link colour is "GDS blue" - clearly darker. "light blue" is the colour I'm referring to.

**Comment by fofr** [comment]
Ah, sorry, that makes more sense. Those two blues are almost the same, I agree there should be one colour.

```
$light-blue: #2b8cc4;
…
$link-active-colour: #2e8aca;
$link-hover-colour: #2e8aca;
```

**Comment by timpaul** [comment]
:+1:

**Comment by gemmaleigh** [comment]
Is there a preference for either of these two blues?

We can either set `$light-blue` to be `#2e8aca`, removing `#2b8cc4` or set `$link-active-colour` and `$link-hover-colour` to be `$light-blue`.

![colour gov uk elements - light blue](https://cloud.githubusercontent.com/assets/417754/12611120/120aa07c-c4e3-11e5-9b9a-3c74441e144d.png)

![colour gov uk elements - hover](https://cloud.githubusercontent.com/assets/417754/12611113/0c4a1154-c4e3-11e5-8fcf-3f93e84b1f6e.png)

**Comment by alextea** [comment]
I think we should set `$link-active-colour` and `$link-hover-colour` to be `$light-blue`.

**Comment by markhurrell** [comment]
+1 to what @alextea says, as long as they have the same colour contrast

**Comment by joelanman** [comment]
@markhurrell contrast to what?

**Comment by stephenjoe1** [comment]
@joelanman To the white background I'm guessing.

**Comment by joelanman** [comment]
right - could be to the normal link or body text colours
