### ISSUE TITLE
update jquery object names to use a $ prefix

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_frontend_toolkit#241]
In the section on [JavaScript modules](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/javascript.md#usage), the variables `container` and `element` look like they are jQuery objects.

In the [style guide](https://github.com/alphagov/styleguides/blob/master/js.md#jquery) the guidance is to use $ prefixes to denote jQuery objects. Should we update the guidance here to reflect that?

**Comment by fofr** [comment]
Yep, this should be updated to match style guide.

**Comment by gemmaleigh** [comment]
@joelanman This has been fixed in #282. Can you please review?
