### ISSUE TITLE
Line height too tight around the BETA / ALPHA tags in phase banners at mobile sizes

### ISSUE THREAD

**Issue by andymantell** [alphagov/govuk_frontend_toolkit#263]
As reported in LandRegistry/land-registry-elements#11 the line height around the phase tags is a bit tight at mobile sizes, so when the text wraps to a new line it butts up against the bottom of the phase tag. See screenshot for example:

![image](https://cloud.githubusercontent.com/assets/134642/13468857/ad4f8eb0-e09c-11e5-840c-40b25a56a4d8.png)

**Comment by alextea** [comment]
Hmmm, I vaguely remember fixing this a long time ago, so that the text wraps under "This". I will investigate!
