### ISSUE TITLE
Possible bug in selection-buttons.js

### ISSUE THREAD

**Issue by glenjamin** [alphagov/govuk_frontend_toolkit#267]
Hello!

We've just started using eslint, and it's flagged up a possible issue in `selection-buttons.js` - I think it's correct.

The reported error is that `$elms` https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/selection-buttons.js#L9 is not used.

It's assigned a little further down https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/selection-buttons.js#L19 - but then this variable is never used.

I think it should be `this.$elms` if I'm following correctly.

**Comment by gemmaleigh** [comment]
This was fixed in  #303.

**Comment by nickcolley** [comment]
Thanks @glenjamin for raising 👍  😄
