### ISSUE TITLE
'accordian' should be 'accordion'

### ISSUE THREAD

**Issue by chrisns** [alphagov/govuk_frontend_toolkit#288]
simple misspelling but I guess fixing it constitute a breaking change :(

https://github.com/alphagov/govuk_frontend_toolkit/blob/master/images/accordian-arrow-2x.png
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/images/accordian-arrow.png

**Comment by nickcolley** [comment]
One alternative we could consider is inlining the image within the CSS (base64), I suspect the cost of the HTTP request could be higher than the cost of inlining but would be worth testing.

**Comment by esr360** [comment]
+1. The breaking change is worth it imo, spelling it accordian is a pet peeve of mine.

**Comment by gemmaleigh** [comment]
Alternatively, submit a pull request to duplicate these images with the correct spelling of 'accordion`. 

As the [incorrect spelling isn't used in many places](https://github.com/search?utf8=%E2%9C%93&q=org%3Aalphagov+accordian&type=Code&ref=searchresults), these can be updated once a set of images with the correct name exist here.

**Comment by gemmaleigh** [comment]
This was fixed in #345.
