### ISSUE TITLE
latest-release branch does not point at latest-release

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_frontend_toolkit#314]
https://github.com/alphagov/govuk_frontend_toolkit/tree/latest-release

Should happen here https://github.com/alphagov/govuk_frontend_toolkit/blob/master/jenkins.sh#L25 but seems to be broken now..

**Comment by 36degrees** [comment]
This is working correctly since we moved to Travis.

Please re-raise if you happen to notice it happening again 👍
