### ISSUE TITLE
Test across our supported browsers

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_frontend_toolkit#325]
We should run our tests in the different environments that we support https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices

This should not replace manual testing where appropriate but will catch simple issues like https://github.com/alphagov/govuk_frontend_toolkit/pull/323 and more complex issues in the future (if we used a ES5 feature without polyfilling for example)

I was thinking we could use sauce labs' free open source tier.

I'm looking into this but raising encase I don't have the time. 👍

**Comment by nickcolley** [comment]
@tombye just an example, I've stopped commits from being merged because they're using ES6 without the author realising it but we could easily miss that.

**Comment by tombye** [comment]
@nickcolley anything you can link to? Might help future story writing to have examples to point to.

**Comment by nickcolley** [comment]
(Shared an example with @tombye directly since the purpose of this issue is not to make anyone feel like it's their fault but rather that anyone contributing could make this easy mistake)

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so given that we've not been able to reproduce this I'm going to close this.
