### ISSUE TITLE
Should provided variables have `!default` flag?

### ISSUE THREAD

**Issue by esr360** [alphagov/govuk_frontend_toolkit#331]
You'll have to forgive my lack of confidence with this issue, but should variables within the toolkit (e.g. https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_grid_layout.scss#L6) have the `!default` flag?

If I'm including the toolkit as a git submodule, I don't want to be touching any of the source files, but I may want to override some of the values. 

If so, I am happy to go through everything and create a pull request.

**Comment by hbweb** [comment]
@esr360 - this is exactly what I'm after atm. I want to override this default container's width but don't want to mess up with the source file. Any suggestion ? tks

**Comment by robinwhittleton** [comment]
@esr360 why don’t you go ahead with a PR. Can review next week.

**Comment by igloosi** [comment]
Hi @esr360,
thank you for the suggestion. We're building the next phase of government frontend and are looking at which variables are in the public API. 
As this is quite an old issue, I'd like to close it unless there are any objections.
