### ISSUE TITLE
Mixing of semi-colon styles can cause errors

### ISSUE THREAD

**Issue by tombye** [alphagov/govuk_frontend_toolkit#338]
The [Show/Hide content module](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/show-hide-content.js) was written with [the standardJS style of semicolon use](http://standardjs.com/rules.html#semicolons). All our other GOVUK modules use the [JSLint style](http://jslint.com/help.html#semicolon) and combining the two can cause errors.

For example, if you have the Show/Hide content module followed by the Stick-at-top-when-scrolling module, you get this:

End of Show/Hide content module:

```
  GOVUK.ShowHideContent = ShowHideContent
  global.GOVUK = GOVUK
})(window)
```

Start of Stick-at-top-when-scrolling module:

```
(function (global) {
  "use strict";
```

...which causes this error:

```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(...) is not a function
```

I think the parser is seeing only line breaks between `})(window)` and `(function (global) {` so assumes you mean:

```
(function () { ... })(window)(function (global) { ... })
```

`(function () { ... })(window)` doesn't return a function so it breaks.

We've solved this on Digital Marketplace by adding a semicolon after the Show/Hide content module block but having a project-specific fix for this isn't ideal.

**Comment by robinwhittleton** [comment]
https://github.com/alphagov/govuk_frontend_toolkit/pull/334 (that @tvararu referenced) lints every JS file with Standard. This fixes this issue. Looking at the original example, both show-hide-content
and stick-at-top-when-scrolling start with the same `;(function (global) {`.
