### ISSUE TITLE
Error messages and colour blindness

### ISSUE THREAD

**Issue by adotellison** [alphagov/govuk_frontend_toolkit#352]
While working with a follow colleague on an error message he pointed out that the current border colour looks black to him.  He has a level of colour blindness, and this red/black problem was confirmed by another person with colour blindness. More research may be required, but I want to see if we could move to using the lighter red (#df3034) for errors, maybe keeping the dark red for just the text?

**Comment by robinwhittleton** [comment]
Hi @adotellison, thanks for the report! Can you give us a link (or screenshot) of a page where your colleague is experiencing this?

**Comment by robinwhittleton** [comment]
Sorry, just found your message on DSD. Will review.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this.

If you believe this is still an issue please add it to the [Design System backlog issue for Error message](https://github.com/alphagov/govuk-design-system-backlog/issues/47).
