### ISSUE TITLE
Question about site width container

### ISSUE THREAD

**Issue by hbweb** [alphagov/govuk_frontend_toolkit#360]
Hi team - just wonder if there is away to overwrite $site-width parameter in order to make container's width wider without editing _grid_layout.scss directly? We're developing web-based application (not public facing site) so ideally want to get wider layout etc. 

Also, Has anyone tried to use Bootstrap v3 with govuk elements and govuk_frontend_toolkit? 

Thanks

**Comment by robinwhittleton** [comment]
The first part of this will be answered by https://github.com/alphagov/govuk_frontend_toolkit/issues/331 (I don’t see that being a problem but I’ll check with people today).

The second part: running GOV.UK assets alongside Bootstrap isn’t a supported scenario. What are you planning to use Bootstrap for?

**Comment by hbweb** [comment]
Thanks @robinwhittleton - it would be great if it is possible to override just like the image path etc. 
``` $path: "/public/images/"; ```

For the second part: We're thinking about utilise some bootstrap's components for our web based application which has so many features and the team want to fit them all in a page with minimal clicks. Also, we only target desktop for this internal project.

**Comment by fofr** [comment]
@hbweb Our current admin UI is based on bootstrap which includes some admin patterns: github.com/alphagov/govuk_admin_template. That _might_ be useful.

It’s lagging behind our public patterns however.

**Comment by hbweb** [comment]
Blimey! this is amazing Paul @fofr, thanks for that - I will take a look and see if we can bring it into our Angular 2 application.
Re public patterns, there are some forms and pages need to be built, seems to be challenging when PO wants to have all visible on the screen.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this given the lack of activity.
