### ISSUE TITLE
Bug or potential issue - show-hide-content.js

### ISSUE THREAD

**Issue by paulmsmith** [alphagov/govuk_frontend_toolkit#366]
Hi,

Following up from a discussion with @dsingleton on XGOV Slack. I noticed a slight issue with the `show-hide-content.js` code.

If you [examine line 83](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/show-hide-content.js#L83) you will see there is an assumption that the '[Conditionally revealing content](http://govuk-elements.herokuapp.com/form-elements/#form-toggle-content)' pattern will existing within a `form` element.

As I was quickly hacking together a prototype within the the govuk prototyping kit, I hadn't wrapped the markup in a form element and it broke silently (no errors or console warnings). It's an edge case  but as there is now a firm movement toward modular builds of components this could bite people.

Simple short term suggestion, check for existence of a form element, else console log a developer friendly message.

Longer term, assume this will be replaced by what's delivered in GOVUK Front-end?

**Comment by robinwhittleton** [comment]
@gemmaleigh bumped into this when adding radio buttons to GOV.UK Frontend – the selection button JS assumes a form as well. In that case we decided that we can drop the JS entirely given a change in markup, but here we probably just need a check for the existence of a form ancestor. Something like this might work?

```
var $form = $control.closest('form')
var $radios = $form.length ? $form.find(selector) : $(selector)
```

**Comment by paulmsmith** [comment]
@robinwhittleton That looks fine to me. What's the reason for using closest? To restrict the affected radios to just those within the form that they are situated?

**Comment by robinwhittleton** [comment]
Yes. Imagine a situation where you have two sets of radios with the same `name` attributes. Outside of a form or within the same form they’ll share the selected state toggling behaviour. In two seperate forms they’ll maintain two seperate toggle states.

**Comment by paulmsmith** [comment]
I thought so but my brain was failing me. :) 👍

**Comment by paulmsmith** [comment]
Nice. +1
