### ISSUE TITLE
Proposal: add a 'positive' colour.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_frontend_toolkit#386]
There are cases where it's useful to have a colour with a semantic meaning of 'positive'.

We already have `error_colour` which is a good red for 'negative' - but we don't have a counterpart.

We could use an existing colour, or make a new colour. Either way, a semantic SASS name would be good.

The closest colour would be `button_colour`. An alternate would be #008800 which is the green used by petitions. It's warmer, which feels more positive to me.

![screen shot 2017-02-27 at 16 55 19](https://cloud.githubusercontent.com/assets/2204224/23370781/b83edafe-fd0d-11e6-9b43-f1cc32d9f820.png)

Thoughts?

**Comment by nickcolley** [comment]
@edwardhorsford since this is in response to 'done' pages' use of turquoise, should we show how this colour would be used and also see if we should deprecate the turquoise?

**Comment by edwardhorsford** [comment]
@nickcolley it's related, but isn't in response to that - it's something I've thought about a few times before.

**Comment by igloosi** [comment]
@edwardhorsford shall we raise this in Frontend and close here?

**Comment by edwardhorsford** [comment]
@igloosi yes that's probably a good idea.

**Comment by igloosi** [comment]
closing in favour of issue in govuk-frontend
