### ISSUE TITLE
Proposal: listen for change events rather than click events in show-hide-content.js

### ISSUE THREAD

**Issue by pcraig3** [alphagov/govuk_frontend_toolkit#392]
This is a bit odd because this problem doesn't exist right now in the [`show-hide-content.js`](https://github.com/alphagov/govuk_frontend_toolkit/blob/cf5efa4c0a2eb59e50b8f7928ed09c4649dd95f4/javascripts/govuk/show-hide-content.js) code, but it seems like a gotcha just waiting to trip up anyone thinking of extending it (for example, it happened to me).

Inside the `click` event for a radio, the clicked radio element will give back different values of `.checked` depending on whether it has been clicked in a browser or a `.click()` event.

-> If it has been clicked in a browser, `this.checked` returns true
-> If it has been clicked using `.click()`, `this.checked` returns false

[I've done up a little demo on jsfiddle](https://jsfiddle.net/ayyjvx3v/).

It seems like [checkboxes used to behave the same way](https://www.bennadel.com/blog/1525-jquery-s-event-triggering-order-of-default-behavior-and-triggerhandler.htm), until a few years ago when this behaviour was changed ([here's the jQuery bug report](https://bugs.jquery.com/ticket/3827)).  

Additionally, it looks like the latest version of jQuery (version 3.2.0) doesn't do this anymore ([here's the commit](https://github.com/jquery/jquery/commit/b442abacbb8464f0165059e8da734e3143d0721f)).  

I think we can call this a bug.

We're not checking if radios are checked anywhere inside the code, although [we are for checkboxes](https://github.com/alphagov/govuk_frontend_toolkit/blob/cf5efa4c0a2eb59e50b8f7928ed09c4649dd95f4/javascripts/govuk/show-hide-content.js#L100).  Seems like it might be a problem we run into in the future.

There are different ways to fix this -- these are a few that occurred to me:
- we can set a timeout of `1 ms` before [calling the `handler` function](https://github.com/alphagov/govuk_frontend_toolkit/blob/cf5efa4c0a2eb59e50b8f7928ed09c4649dd95f4/javascripts/govuk/show-hide-content.js#L114)
- we can try to differentiate between a mouse click and a browser click
- we can listen to `change` events rather than `click` events

I ran into this problem on the digitalmarketplace frontend toolkit (where we need to know the `checked` state of a radio button) and [I went with listening for change events](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/322/commits/934dd68e4ab97b037b5342b34e8996ce499e4c6a) because it seemed the most lightweight change and I couldn't think of a situation where we would get the wrong behaviour.  We don't get events anymore for multiple clicks on already-checked radios but I can't think of a situation where we would care about that.

What do we think?

**Comment by tombye** [comment]
Just out of curiosity, why is support for click events fired by JS useful? I'm assuming it's to support selenium-like browser testing (like capybara) but be good to be sure.

**Comment by 36degrees** [comment]
Thanks for raising, @pcraig3.

Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this.
