### ISSUE TITLE
selection-buttons.js doesn't respect the disabled="disabled" attribute

### ISSUE THREAD

**Issue by khaledzaidan** [alphagov/govuk_frontend_toolkit#394]
If a radio button or checkbox has the disabled="disabled" attribute, selection-buttons.js still allows the user to tick/select and untick/unselect.

**Comment by khaledzaidan** [comment]
Here's a patch for a simple fix. I'm not sure if this is the best way to do it, but at least it's something that works.

`diff --git a/javascripts/govuk/selection-buttons.js b/javascripts/govuk/selection-buttons.js
index d090d26..512b558 100644
--- a/javascripts/govuk/selection-buttons.js
+++ b/javascripts/govuk/selection-buttons.js
@@ -83,6 +83,10 @@
   }
   SelectionButtons.prototype.getClickHandler = function () {
     return function (e) {
+      if ($(e.target).attr('disabled') == 'disabled') {
+        return;
+      }
+
       this.markSelected($(e.target))
     }.bind(this)
   }
`

**Comment by robinwhittleton** [comment]
Hi Khaled, I’ve been working on a revised version of the checkboxes / radios that respect the `disabled` attribute and don’t need for selection-buttons.js (at a cost of reworking the markup). We’re currently fighting some Travis problems but once we fix those we’ll release a new version of GOV.UK Elements (probably 3.0.1) that’ll include those.

**Comment by robinwhittleton** [comment]
We’ve updated Elements to no longer need selection-buttons.js for radios and checkboxes, and [marked the JS as deprecated](https://github.com/alphagov/govuk_frontend_toolkit/pull/389). There’s also [styling in elements to respect `disabled`](https://github.com/alphagov/govuk_elements/blob/b2d5c0f8470314c34e53d66dd2998fd4735e84eb/public/sass/elements/forms/_form-multiple-choice.scss#L115). Does this answer your need?

**Comment by igloosi** [comment]
HI, @khaledzaidan 
as this file has been deprecated in favour of new radios and checkboxes (see above response) Would you object to me closing this issue?

**Comment by khaledzaidan** [comment]
Ah, yes, please go ahead. If the file has been deprecated, then there's not
much point of this ticket anymore.

Thanks :)
