### ISSUE TITLE
frontend toolkit is not namespaced

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/govuk_frontend_toolkit#415]
it's really hard to trace where things are coming from, as a lot of our libraries are not namespaced in our import statements
implementing namespacing would make it much easier to reason about our codebases

**Comment by fofr** [comment]
We should spike what this looks like and consider the impact on users.

**Comment by igloosi** [comment]
Hi @mcgoooo,
thanks for raising this. As referenced above we're implementing namespacing in the new product.
Mind if I close this issue?

**Comment by mcgoooo** [comment]
@igloosi absolutely not, i'm not employed by gds anymore and icant even remember what this is
