### ISSUE TITLE
ARIA attributes set by GOVUK.ShowHideContent are invalid

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_frontend_toolkit#419]
Raised on [GOV.UK elements](https://github.com/alphagov/govuk_elements/issues/455).

**Comment by LJWatson** [comment]
Removing the aria-expanded attribute will solve one problem and introduce another. Without the attribute, there is no way for screen reader users to know that the show/hide functionality is there.

As noted in alphagov/govuk_elements#455, I don't think using radio buttons as a show/hide trigger is a good design pattern (at least not for screen reader users). The level of support across browsers for aria-expanded on a radio button or checkbox is also unknown.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this as it's not actionable.

There's a lot of valuable discussion on the [related issue over in Elements](https://github.com/alphagov/govuk_elements/issues/455) – we'll try to capture that as best as we can before we close that.
