### ISSUE TITLE
Update stageprompt to use universal tracker

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_frontend_toolkit#423]
I believe we could use https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/analytics/google-analytics-universal-tracker.js#L69 so that stageprompt is less clever here https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/stageprompt.js#L64

**Comment by igloosi** [comment]
Is this still in use?

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this.
