### ISSUE TITLE
Publishing to govuk_frontend_toolkit_gem and govuk_frontend_toolkit_npm is failing

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_frontend_toolkit#427]
https://travis-ci.org/alphagov/govuk_frontend_toolkit#L835

Both the govuk_frontend_toolkit_gem and govuk_frontend_toolkit_npm haven't been updated to 7.0.0.

**Comment by gemmaleigh** [comment]
This was fixed by updating the Travis access token which is used to trigger the downstream builds for both govuk_frontend_toolkit_npm and govuk_frontend_toolkit_gem. 

The previous token was associated with @alexmuller's account, which was why the initial release of v7.0.0 failed to trigger the downstream jobs.

A new token was added to Travis' repo settings, this token is owned by the github-patterns-and-tools-ci user.

**Comment by alexmuller** [comment]
Sorry! Good fix though 😄 💯
