### ISSUE TITLE
Question about conditional logic on {{ data[] }}

### ISSUE THREAD

**Issue by deckchairuk** [alphagov/govuk_frontend_toolkit#437]
Hello, sorry if this is the wrong place for this but I am unable to join the Slack channel.

I need to run a conditional on some data but I'm not sure how using the templating language. Could anyone help?

**Comment by deckchairuk** [comment]
Solved using nunjucks documentation (had to work it out myself partly. 

For anyone else that comes to this looking for help you can run conditionals on the data tag like so:

{{ "Yes" if data['dataName']}}

**Comment by joelanman** [comment]
thanks for updating! For future reference, the prototype kit repo is over here:

https://github.com/alphagov/govuk_prototype_kit
