### ISSUE TITLE
Number names used in CSS as opposed to digits

### ISSUE THREAD

**Issue by stuaxo** [alphagov/govuk_frontend_toolkit#441]
The English names in this project look nice and readable at first, but if you want to do any automation around column output / numbering it adds a completely unnecessary layer (your code now has to generate or parse English numbers).

The system bootstrap uses is terse, but more amenable to automation.

**Comment by igloosi** [comment]
@stuaxo I don't think we're going to embark on a name change anytime soon to be honest

**Comment by stuaxo** [comment]
Awesome, thanks.

I don't know how plausible it is, but it may be worth considering newer technologies like Flexbox and CSS grid too.

**Comment by igloosi** [comment]
Hi, yes, we're looking at @supports cascade.
Would you mind if i close this issue?

**Comment by stuaxo** [comment]
NP, look forward to reading about the new product :)
