### ISSUE TITLE
Google analytics error

### ISSUE THREAD

**Issue by bendiggle** [alphagov/govuk_frontend_toolkit#456]
Currently our google analytics is not working for version `7.4.2`.

It is erroring here: https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/analytics/analytics.js#L102, where `location` is undefined. 

Below is an image of the errors in the browser.

<img width="1280" alt="screen shot 2018-03-06 at 16 13 54" src="https://user-images.githubusercontent.com/11047071/37043779-80b4a5ca-2159-11e8-9168-615998a7194b.png">

Any ideas?

**Comment by 36degrees** [comment]
Thanks for raising this. That function is called from `trackPageview` which passes [`window.location`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) as the location argument.

The error you're seeing suggests that `window.location` is undefined, which would be unusual – is there anything you're doing in your code that could be causing this?

**Comment by bendiggle** [comment]
Hi @36degrees, thanks for getting back to me. This problem has been resolved. It was an issue with our webpack config.
Thanks again!
