### ISSUE TITLE
Duplicate OGL links

### ISSUE THREAD

**Issue by jbuller** [alphagov/govuk_frontend_toolkit#457]
The OGL logo and the link in the adjacent text are linked to the same page.  When adjacent links go to the same location this results in additional navigation and repetition for keyboard and screen reader users. Remove the link from the logo (is it required at all?)

Fixing this would also avoid help staff people checking websites for accessibility, using tools such as WAVE and Axe. It shows up as a warning. Inexperienced people then spend time investigating and worrying about it. It also looks so much better to be able to show stakeholders a report with 0 errors and 0 warnings, than to always have a 1 there by default.

**Comment by nickcolley** [comment]
Hey @jbuller 

We're currently making a new version of the footer for the new GOV.UK Frontend project.

I noticed the same thing you're describing and decided to remove the duplicate link and turn it into a presentational element.

You can see this work here: https://github.com/alphagov/govuk-frontend/pull/569#discussion_r172879983

Keep in mind GOV.UK Frontend is not yet public but will replace govuk_frontend_toolkit.

We could port this to change back to https://github.com/alphagov/govuk_template or close this issue.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, which wouldn't include addressing this, so I'm going to close this.

As Nick mentioned, this has been addressed in GOV.UK Frontend, which is now in public beta.
