### ISSUE TITLE
Google Analytics date regex is very specific

### ISSUE THREAD

**Issue by lewisnyman** [alphagov/govuk_frontend_toolkit#469]
Hi, I was just testing out the date regex that strips PII from Google Analytics events. It seems like the regex only captures dates in the format: `XXXX-XX-XX`

My initial test was XX/XX/XXXX, which wasn't being caught. It might be worth making the regex a bit more flexible?

**Comment by nickcolley** [comment]
Related conversation about flexibility: https://github.com/alphagov/govuk_frontend_toolkit/pull/466#issuecomment-405517391

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this.

GOV.UK Design System (and GOV.UK Frontend) does not provide any analytics functionality, and as far as I know there are currently no plans to provide this either as part of Frontend nor as a separate library.
