### ISSUE TITLE
What should be used instead of govuk_frontend_toolkit?

### ISSUE THREAD

**Issue by byzantime** [alphagov/govuk_frontend_toolkit#475]
I found this repo via govuk-template-flask-skeleton, which pulls this repo in as a git submodule.

It's great there's a notice saying that govuk_frontend_toolkit has been deprecated - but it'd be even more helpful if it could also say what superseded the toolkit.

Can the project description or readme.md be updated to point to this project's replacement?

**Comment by igloosi** [comment]
HI @byzantime 

the readme currently says

> The GOV.UK Design System launched on 22 June 2018
> The Government Digital Service (GDS) is retiring GOV.UK Frontend Toolkit following the launch of the GOV.UK Design System. GOV.UK Frontend Toolkit will remain available to you if you are currently using it but will no longer be maintained. GDS will only roll out major bug fixes and security patches.
> 
> For new projects, you can get all of the information about GOV.UK styles, components and patterns in the GOV.UK Design System.

Does this answer your question?

**Comment by joelanman** [comment]
In particular, GOV.UK Frontend is the codebase you're probably looking for - there's a getting started guide here:

https://design-system.service.gov.uk/get-started/

**Comment by joelanman** [comment]
closing, but feel free to re-open if we've not fully answered your question
