### ISSUE TITLE
Is there any way to integrate to Angular?

### ISSUE THREAD

**Issue by siva563** [alphagov/govuk_frontend_toolkit#483]
Is there any way to use Styles sheets in the Angular Project?

Could you please help me if possible.

**Comment by andysellick** [comment]
Hi @siva563. This project is deprecated and should not be used. You should use https://design-system.service.gov.uk/ instead.

**Comment by nickcolley** [comment]
Heya :)

As Andy says this project is no longer maintained but we can support you to use the GOV.UK Design System.

Feel free to get in touch: https://design-system.service.gov.uk/get-in-touch
