### ISSUE TITLE
The deploy credentials seem to no longer work

### ISSUE THREAD

**Issue by kevindew** [alphagov/govuk_frontend_toolkit#488]
With the merge of https://github.com/alphagov/govuk_frontend_toolkit/pull/487 I've noticed the [deploy script is failing](https://travis-ci.com/github/alphagov/govuk_frontend_toolkit/builds/202030251): 

```
Add config for alphagov/alphagov/govuk_frontend_toolkit
Check to see if the version file has been updated
Creating new tag: v9.0.1
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Already up to date!
HEAD detached at e46f38e
nothing to commit, working tree clean
Dropped refs/stash@{0} (3eb97e1b7702698d638ac2bb88a16730791e441a)
Script failed with status 128
failed to deploy
```

I'm assuming this is because the [GOV.UK Design System CI](https://github.com/govuk-design-system-ci) keys no longer contains the value used by this repo and needs updating as per: https://github.com/alphagov/govuk_frontend_toolkit/pull/450

If this is all a total pain to fix let me know and I'll rollback my [changes](https://github.com/alphagov/govuk_frontend_toolkit_gem/pull/20) - they're nice to have changes rather than something essential.

**Comment by lfdebrux** [comment]
Hi @kevindew, sorry it took us so long to look at this!

I think I've resolved part of the issue; I think a new release v9.0.1 with your changes has gone out:

https://github.com/alphagov/govuk_frontend_toolkit/releases/tag/v9.0.1

**Comment by lfdebrux** [comment]
For some reason the deploy script is still failing, but in a different way :thinking:

```
$ test $TRAVIS_TEST_RESULT = 0
dpl_1
1.67s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
2.91s
dpl.1
Installing deploy dependencies
dpl.2
Preparing deploy
dpl.3
Deploying application
access deniedaccess denied
Already up to date!
HEAD detached at e46f38e
nothing to commit, working tree clean
Dropped refs/stash@{0} (0f38dba2a9ef7a834f7378de1f704504169b05ae)
```

https://travis-ci.com/github/alphagov/govuk_frontend_toolkit/builds/202030251

**Comment by lfdebrux** [comment]
Yeah, as suspected, the gem hasn't gone out

**Comment by lfdebrux** [comment]
I've fixed the gem deploy keys as well, govuk_frontend_toolkit has been published to RubyGems

https://rubygems.org/gems/govuk_frontend_toolkit/versions/9.0.1
