### ISSUE TITLE
Module build failed.

### ISSUE THREAD

**Issue by palanisamy-emis** [alphagov/govuk_frontend_toolkit#489]
Package Json dependencies:
  "govuk-frontend": "^4.0.1",
  "govuk_frontend_toolkit": "^9.0.1",
 "govuk_frontend_toolkit_test_runner":"https://github.com/alphagov/govuk_frontend_toolkit.git#commit=e46f38ebdeef063c601e40580a93e0f5cb8a20aa",

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../../node_modules/govuk_frontend_toolkit/stylesheets/design-patterns/separator.png' in '/var/www/assets/css'
    at finishWithoutResolve (/var/www/node_modules/enhanced-resolve/lib/Resolver.js:309:18).

Could some one assist me on fixing this issue?

**Comment by andysellick** [comment]
`govuk_frontend_toolkit` has been replaced by the GOV.UK Design System and as such is no longer supported. We suggest you migrate https://github.com/alphagov/govuk_frontend_toolkit#readme.
