### ISSUE TITLE
External link icon for larger font sizes

### ISSUE THREAD

**Issue by annapowellsmith** [alphagov/govuk_frontend_toolkit#90]
Please could we have an additional external link icon to use with larger font sizes?

We have a design that has a `rel="external"` link in 24px and it would be great to use the external link icon with it. The current image isn't big enough to look good. 

https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss#L334-400 is the relevant code.

**Comment by alicebartlett** [comment]
[From the frontend meeting] For any new external link styles, please raise a PR on the front end toolkit, we're happy to merge if the need is made clear.

**Comment by esr360** [comment]
We have ended up using an SVG icon for the external link icon due to the numerous cases of sizes/colors we require it in. Moving forward I can't see any other option than to provide SVG.

**Comment by selfthinker** [comment]
Getting #293 would also solve this issue as that would remove all external link icons.

**Comment by gemmaleigh** [comment]
External link icons were removed in #293, so this can be closed.
